export const BRAND_NAME = "The Clear Contract Nigeria";
export const BRAND_SHORT = "TCCN";
export const GOV_FULL = "Federal Republic of Nigeria";
export const CONTACT_EMAIL = "contact@clearcontract.ng";
export const WEBSITE = "clearcontract.ng";

export const NIGERIAN_STATES = [
  "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue",
  "Borno", "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "FCT",
  "Gombe", "Imo", "Jigawa", "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi",
  "Kwara", "Lagos", "Nasarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo",
  "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara",
];

export const SECTORS = [
  { id: "roads" as const, label: "Roads & Bridges" },
  { id: "health" as const, label: "Health" },
  { id: "education" as const, label: "Education" },
  { id: "power" as const, label: "Power & Energy" },
  { id: "water" as const, label: "Water & Sanitation" },
  { id: "housing" as const, label: "Housing" },
  { id: "security" as const, label: "Security" },
  { id: "agriculture" as const, label: "Agriculture" },
  { id: "digital" as const, label: "Digital Infrastructure" },
  { id: "rail" as const, label: "Rail & Transport" },
];

export const GEO_ZONES = [
  { id: "north-west" as const, label: "North West" },
  { id: "north-east" as const, label: "North East" },
  { id: "north-central" as const, label: "North Central" },
  { id: "south-west" as const, label: "South West" },
  { id: "south-east" as const, label: "South East" },
  { id: "south-south" as const, label: "South South" },
  { id: "fct" as const, label: "FCT Abuja" },
];

export const LANGUAGES: { id: string; label: string; native: string }[] = [
  { id: "en", label: "English", native: "English" },
  { id: "ha", label: "Hausa", native: "Hausa" },
  { id: "yo", label: "Yoruba", native: "Yorùbá" },
  { id: "ig", label: "Igbo", native: "Igbo" },
  { id: "pcm", label: "Pidgin", native: "Naija Pidgin" },
];

export const ROLES: { id: string; label: string }[] = [
  { id: "citizen", label: "Citizen / CSO" },
  { id: "executive", label: "Presidency / Executive" },
  { id: "ministry", label: "Ministry / MDA" },
  { id: "contractor", label: "Contractor Portal" },
  { id: "auditor", label: "Auditor / EFCC" },
];

export const STATUS_COLORS: Record<string, string> = {
  planning: "bg-slate-400",
  tender: "bg-amber-400",
  awarded: "bg-blue-400",
  active: "bg-emerald-400",
  delayed: "bg-orange-400",
  completed: "bg-green-600",
  abandoned: "bg-red-500",
};

export const RISK_COLORS: Record<string, string> = {
  low: "bg-emerald-500",
  medium: "bg-amber-500",
  high: "bg-orange-500",
  critical: "bg-red-500",
};

export const TRUST_COLOR = (score: number) => {
  if (score >= 80) return "text-emerald-600";
  if (score >= 60) return "text-amber-600";
  if (score >= 40) return "text-orange-600";
  return "text-red-600";
};

export const NIN_LENGTH = 11;
export const NIN_PATTERN = /^\d{11}$/;

export const LGAS_BY_STATE: Record<string, string[]> = {
  "Abia": ["Aba North", "Aba South", "Arochukwu", "Bende", "Ikwuano", "Isiala Ngwa North", "Isiala Ngwa South", "Isuikwuato", "Obi Ngwa", "Ohafia", "Osisioma", "Ugwunagbo", "Ukwa East", "Ukwa West", "Umuahia North", "Umuahia South", "Umu Nneochi"],
  "Adamawa": ["Demsa", "Fufure", "Ganye", "Gayuk", "Gombi", "Grie", "Hong", "Jada", "Larmurde", "Madagali", "Maiha", "Mayo Belwa", "Michika", "Mubi North", "Mubi South", "Numan", "Shelleng", "Song", "Toungo", "Yola North", "Yola South"],
  "Akwa Ibom": ["Abak", "Eastern Obolo", "Eket", "Esit Eket", "Essien Udim", "Etim Ekpo", "Etinan", "Ibeno", "Ibesikpo Asutan", "Ibiono Ibom", "Ika", "Ikono", "Ikot Abasi", "Ikot Ekpene", "Ini", "Itu", "Mbo", "Mkpat Enin", "Nsit Atai", "Nsit Ibom", "Nsit Ubium", "Obot Akara", "Okobo", "Onna", "Oron", "Oruk Anam", "Udung Uko", "Ukanafun", "Uruan", "Urue Offong Oruko", "Uyo"],
  "Anambra": ["Aguata", "Anambra East", "Anambra West", "Anaocha", "Awka North", "Awka South", "Ayamelum", "Dunukofia", "Ekwusigo", "Idemili North", "Idemili South", "Ihiala", "Njikoka", "Nnewi North", "Nnewi South", "Ogbaru", "Onitsha North", "Onitsha South", "Orumba North", "Orumba South", "Oyi"],
  "Bauchi": ["Alkaleri", "Bauchi", "Bogoro", "Damban", "Darazo", "Dass", "Gamawa", "Ganjuwa", "Giade", "Itas/Gadau", "Jama'are", "Katagum", "Kirfi", "Misau", "Ningi", "Shira", "Tafawa Balewa", "Toro", "Warji", "Zaki"],
  "Bayelsa": ["Brass", "Ekeremor", "Kolokuma/Opokuma", "Nembe", "Ogbia", "Sagbama", "Southern Ijaw", "Yenagoa"],
  "Benue": ["Ado", "Agatu", "Apa", "Buruku", "Gboko", "Guma", "Gwer East", "Gwer West", "Katsina-Ala", "Konshisha", "Kwande", "Logo", "Makurdi", "Obi", "Ogbadibo", "Ohimini", "Oju", "Okpokwu", "Otukpo", "Tarka", "Ukum", "Ushongo", "Vandeikya"],
  "Borno": ["Abadam", "Askira/Uba", "Bama", "Bayo", "Biu", "Chibok", "Damboa", "Dikwa", "Gubio", "Guzamala", "Gwoza", "Hawul", "Jere", "Kaga", "Kala/Balge", "Konduga", "Kukawa", "Kwaya Kusar", "Mafa", "Magumeri", "Maiduguri", "Marte", "Mobbar", "Monguno", "Ngala", "Nganzai", "Shani"],
  "Cross River": ["Abi", "Akamkpa", "Akpabuyo", "Bakassi", "Bekwarra", "Biase", "Boki", "Calabar Municipal", "Calabar South", "Etung", "Ikom", "Obanliku", "Obubra", "Obudu", "Odukpani", "Ogoja", "Yakuur", "Yala"],
  "Delta": ["Aniocha North", "Aniocha South", "Bomadi", "Burutu", "Ethiope East", "Ethiope West", "Ika North East", "Ika South", "Isoko North", "Isoko South", "Ndokwa East", "Ndokwa West", "Okpe", "Oshimili North", "Oshimili South", "Patani", "Sapele", "Udu", "Ughelli North", "Ughelli South", "Ukwuani", "Uvwie", "Warri North", "Warri South", "Warri South West"],
  "Ebonyi": ["Abakaliki", "Afikpo North", "Afikpo South", "Ebonyi", "Ezza North", "Ezza South", "Ikwo", "Ishielu", "Ivo", "Izzi", "Ohaozara", "Ohaukwu", "Onicha"],
  "Edo": ["Akoko-Edo", "Egor", "Esan Central", "Esan North-East", "Esan South-East", "Esan West", "Etsako Central", "Etsako East", "Etsako West", "Igueben", "Ikpoba Okha", "Oredo", "Orhionmwon", "Ovia North-East", "Ovia South-West", "Owan East", "Owan West", "Uhunmwonde"],
  "Ekiti": ["Ado Ekiti", "Efon", "Ekiti East", "Ekiti South-West", "Ekiti West", "Emure", "Gbonyin", "Ido Osi", "Ijero", "Ikere", "Ikole", "Ilejemeje", "Irepodun/Ifelodun", "Ise/Orun", "Moba", "Oye"],
  "Enugu": ["Aninri", "Awgu", "Enugu East", "Enugu North", "Enugu South", "Ezeagu", "Igbo Etiti", "Igbo Eze North", "Igbo Eze South", "Isi Uzo", "Nkanu East", "Nkanu West", "Nsukka", "Oji River", "Udenu", "Udi", "Uzo Uwani"],
  "FCT": ["Abaji", "Bwari", "Gwagwalada", "Kuje", "Kwali", "Municipal Area Council"],
  "Gombe": ["Akko", "Balanga", "Billiri", "Dukku", "Funakaye", "Gombe", "Kaltungo", "Kwami", "Nafada", "Shongom", "Yamaltu/Deba"],
  "Imo": ["Aboh Mbaise", "Ahiazu Mbaise", "Ehime Mbano", "Ezinihitte", "Ideato North", "Ideato South", "Ihitte/Uboma", "Ikeduru", "Isiala Mbano", "Isu", "Mbaitoli", "Ngor Okpala", "Njaba", "Nkwerre", "Nwangele", "Obowo", "Oguta", "Ohaji/Egbema", "Okigwe", "Orlu", "Orsu", "Oru East", "Oru West", "Owerri Municipal", "Owerri North", "Owerri West", "Unuimo"],
  "Jigawa": ["Auyo", "Babura", "Biriniwa", "Birnin Kudu", "Buji", "Dutse", "Gagarawa", "Garki", "Gumel", "Guri", "Gwaram", "Gwiwa", "Hadejia", "Jahun", "Kafin Hausa", "Kaugama", "Kazaure", "Kiri Kasama", "Kiyawa", "Maigatari", "Malam Madori", "Miga", "Ringim", "Roni", "Sule Tankarkar", "Taura", "Yankwashi"],
  "Kaduna": ["Birnin Gwari", "Chikun", "Giwa", "Igabi", "Ikara", "Jaba", "Jema'a", "Kachia", "Kaduna North", "Kaduna South", "Kagarko", "Kajuru", "Kaura", "Kauru", "Kubau", "Kudan", "Lere", "Makarfi", "Sabon Gari", "Sanga", "Soba", "Tudun Wada", "Zangon Kataf", "Zaria"],
  "Kano": ["Ajingi", "Albasu", "Bagwai", "Bebeji", "Bichi", "Bunkure", "Dala", "Dambatta", "Dawakin Kudu", "Dawakin Tofa", "Doguwa", "Fagge", "Gabasawa", "Garko", "Garun Mallam", "Gaya", "Gezawa", "Gwale", "Gwarzo", "Kabo", "Kano Municipal", "Karaye", "Kibiya", "Kiru", "Kumbotso", "Kunchi", "Kura", "Madobi", "Makoda", "Minjibir", "Nasarawa", "Rano", "Rimin Gado", "Rogo", "Shanono", "Sumaila", "Takai", "Tarauni", "Tofa", "Tsanyawa", "Tudun Wada", "Ungogo", "Warawa", "Wudil"],
  "Katsina": ["Bakori", "Batagarawa", "Batsari", "Baure", "Bindawa", "Charanchi", "Dan Musa", "Dandume", "Danja", "Daura", "Dutsi", "Dutsin Ma", "Faskari", "Funtua", "Ingawa", "Jibia", "Kafur", "Kaita", "Kankara", "Kankia", "Katsina", "Kurfi", "Kusada", "Mai'Adua", "Malumfashi", "Mani", "Mashi", "Matazu", "Musawa", "Rimi", "Sabuwa", "Safana", "Sandamu", "Zango"],
  "Kebbi": ["Aleiro", "Arewa Dandi", "Argungu", "Augie", "Bagudo", "Birnin Kebbi", "Bunza", "Dandi", "Fakai", "Gwandu", "Jega", "Kalgo", "Koko/Besse", "Maiyama", "Ngaski", "Sakaba", "Shanga", "Suru", "Wasagu/Danko", "Yauri", "Zuru"],
  "Kogi": ["Adavi", "Ajaokuta", "Ankpa", "Bassa", "Dekina", "Ibaji", "Idah", "Igalamela Odolu", "Ijumu", "Kabba/Bunu", "Kogi", "Lokoja", "Mopa Muro", "Ofu", "Ogori/Magongo", "Okehi", "Okene", "Olamaboro", "Omala", "Yagba East", "Yagba West"],
  "Kwara": ["Asa", "Baruten", "Edu", "Ekiti", "Ifelodun", "Ilorin East", "Ilorin South", "Ilorin West", "Irepodun", "Isin", "Kaiama", "Moro", "Offa", "Oke Ero", "Oyun", "Pategi"],
  "Lagos": ["Agege", "Ajeromi-Ifelodun", "Alimosho", "Amuwo-Odofin", "Apapa", "Badagry", "Epe", "Eti-Osa", "Ibeju-Lekki", "Ifako-Ijaiye", "Ikeja", "Ikorodu", "Kosofe", "Lagos Island", "Lagos Mainland", "Mushin", "Ojo", "Oshodi-Isolo", "Shomolu", "Surulere"],
  "Nasarawa": ["Akwanga", "Awe", "Doma", "Karu", "Keana", "Keffi", "Kokona", "Lafia", "Nasarawa", "Nasarawa Egon", "Obi", "Toto", "Wamba"],
  "Niger": ["Agaie", "Agwara", "Bida", "Borgu", "Bosso", "Chanchaga", "Edati", "Gbako", "Gurara", "Katcha", "Kontagora", "Lapai", "Lavun", "Magama", "Mariga", "Mashegu", "Mokwa", "Munya", "Paikoro", "Rafi", "Rijau", "Shiroro", "Suleja", "Tafa", "Wushishi"],
  "Ogun": ["Abeokuta North", "Abeokuta South", "Ado-Odo/Ota", "Egbado North", "Egbado South", "Ewekoro", "Ifo", "Ijebu East", "Ijebu North", "Ijebu North East", "Ijebu Ode", "Ikenne", "Imeko Afon", "Ipokia", "Obafemi Owode", "Odeda", "Odogbolu", "Ogun Waterside", "Remo North", "Sagamu", "Yewa North", "Yewa South"],
  "Ondo": ["Akoko North-East", "Akoko North-West", "Akoko South-East", "Akoko South-West", "Akure North", "Akure South", "Ese Odo", "Idanre", "Ifedore", "Ilaje", "Ile Oluji/Okeigbo", "Irele", "Odigbo", "Okitipupa", "Ondo East", "Ondo West", "Ose", "Owo"],
  "Osun": ["Atakunmosa East", "Atakunmosa West", "Aiyedaade", "Aiyedire", "Boluwaduro", "Boripe", "Ede North", "Ede South", "Egbedore", "Ejigbo", "Ife Central", "Ife East", "Ife North", "Ife South", "Ifedayo", "Ila", "Ilesa East", "Ilesa West", "Irepodun", "Irewole", "Isokan", "Iwo", "Obokun", "Odo Otin", "Ola Oluwa", "Olorunda", "Oriade", "Orolu", "Osogbo"],
  "Oyo": ["Afijio", "Akinyele", "Atiba", "Atisbo", "Egbeda", "Ibadan North", "Ibadan North-East", "Ibadan North-West", "Ibadan South-East", "Ibadan South-West", "Ibarapa Central", "Ibarapa East", "Ibarapa North", "Ido", "Irepo", "Iseyin", "Itesiwaju", "Iwajowa", "Kajola", "Lagelu", "Ogbomosho North", "Ogbomosho South", "Ogo Oluwa", "Olorunsogo", "Oluyole", "Ona Ara", "Orelope", "Ori Ire", "Oyo East", "Oyo West", "Saki East", "Saki West", "Surulere"],
  "Plateau": ["Barkin Ladi", "Bassa", "Bokkos", "Jos East", "Jos North", "Jos South", "Kanam", "Kanke", "Langtang North", "Langtang South", "Mangu", "Mikang", "Pankshin", "Qua'an Pan", "Riyom", "Shendam", "Wase"],
  "Rivers": ["Abua/Odual", "Ahoada East", "Ahoada West", "Akuku Toru", "Andoni", "Asari Toru", "Bonny", "Degema", "Eleme", "Emuoha", "Etche", "Gokana", "Ikwerre", "Khana", "Obio/Akpor", "Ogba/Egbema/Ndoni", "Ogu/Bolo", "Okrika", "Omuma", "Opobo/Nkoro", "Oyigbo", "Port Harcourt", "Tai"],
  "Sokoto": ["Binji", "Bodinga", "Dange Shuni", "Gada", "Goronyo", "Gudu", "Gwadabawa", "Illela", "Isa", "Kebbe", "Kware", "Rabah", "Sabon Birni", "Shagari", "Silame", "Sokoto North", "Sokoto South", "Tambuwal", "Tangaza", "Tureta", "Wamakko", "Wurno", "Yabo"],
  "Taraba": ["Ardo Kola", "Bali", "Donga", "Gashaka", "Gassol", "Ibi", "Jalingo", "Karim Lamido", "Kurmi", "Lau", "Sardauna", "Takum", "Ussa", "Wukari", "Yorro", "Zing"],
  "Yobe": ["Bade", "Bursari", "Damaturu", "Fika", "Fune", "Geidam", "Gujba", "Gulani", "Jakusko", "Karasuwa", "Machina", "Nangere", "Nguru", "Potiskum", "Tarmuwa", "Yunusari", "Yusufari"],
  "Zamfara": ["Anka", "Bakura", "Birnin Magaji/Kiyaw", "Bukkuyum", "Bungudu", "Gummi", "Gusau", "Kaura Namoda", "Maradun", "Maru", "Shinkafi", "Talata Mafara", "Tsafe", "Zurmi"],
};

export const TRUST_BG = (score: number) => {
  if (score >= 80) return "bg-emerald-50 border-emerald-200";
  if (score >= 60) return "bg-amber-50 border-amber-200";
  if (score >= 40) return "bg-orange-50 border-orange-200";
  return "bg-red-50 border-red-200";
};

export const translations: Record<string, Record<string, string>> = {
  en: {
    "app.title": "The Clear Contract Nigeria",
    "app.subtitle": "National Infrastructure & Procurement Transparency Platform",
    "app.tagline": "Open. Accountable. Transparent.",
    "nav.home": "Home",
    "nav.map": "National Map",
    "nav.dashboard": "Dashboard",
    "nav.projects": "Projects",
    "nav.contractors": "Contractors",
    "nav.verify": "Verify Project",
    "nav.export": "Reports & Data",
    "nav.trust": "Trust Matrix",
    "search.placeholder": "Search by project code, contractor, state, MDA...",
    "filter.sector": "Sector",
    "filter.state": "State",
    "filter.status": "Status",
    "filter.risk": "Risk Level",
    "filter.lga": "LGA",
    "filter.zone": "Geo-Political Zone",
    "filter.clear": "Clear Filters",
    "project.total": "Total Projects",
    "project.active": "Active",
    "project.completed": "Completed",
    "project.flagged": "Flagged",
    "project.budget": "Approved Budget",
    "project.released": "Released",
    "project.spent": "Spent",
    "project.trustscore": "Trust Score",
    "project.overview": "Overview",
    "project.financial": "Financial Breakdown",
    "project.inspection": "Site Inspection & AI Verification",
    "project.documents": "Documents & Compliance",
    "project.milestones": "Milestones",
    "contractor.name": "Contractor",
    "contractor.rating": "Performance Rating",
    "contractor.cac": "CAC Registration",
    "contractor.bpp": "BPP Clearance",
    "contractor.contracts": "Contracts",
    "citizen.submit": "Submit Field Report",
    "citizen.upload": "Upload Site Photos",
    "citizen.gps": "GPS Location",
    "citizen.ai": "AI Analysis",
    "citizen.badges": "Your Badges",
    "citizen.reports": "Your Reports",
    "role.switch": "Switch Role",
    "role.citizen": "Citizen / CSO",
    "role.executive": "Presidency / Executive",
    "role.ministry": "Ministry / MDA",
    "role.contractor": "Contractor Portal",
    "role.auditor": "Auditor / EFCC",
    "export.pdf": "Export PDF",
    "export.csv": "Export CSV",
    "export.json": "Export JSON (OCDS)",
    "trust.breakdown": "Trust Score Breakdown",
    "trust.anomalies": "Anomaly Detection",
    "trust.simulator": "Scenario Simulator",
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.close": "Close",
    "common.view": "View Details",
    "common.back": "Back",
  },
  ha: {
    "app.title": "The Clear Contract Nigeria",
    "app.subtitle": "Dandalin Bayyana Ayyukan Gwamnati & Sayayya",
    "app.tagline": "Bude. Mai Lissafi. Bayyane.",
    "nav.home": "Shafi",
    "nav.map": "Taswirar Kasa",
    "nav.dashboard": "Dashboard",
    "nav.projects": "Ayyuka",
    "nav.contractors": "Yan kwangila",
    "nav.verify": "Tabbatar Aiki",
    "nav.export": "Rahotanni & Bayanai",
    "nav.trust": "Amintacce Matrix",
    "search.placeholder": "Nemo ta lambar aiki, dan kwangila, jiha, MDA...",
    "filter.sector": "Sashe",
    "filter.state": "Jiha",
    "filter.status": "Matsayi",
    "filter.risk": "Matsayin Hadari",
    "filter.lga": "Karamar Hukuma",
    "filter.zone": "Yankin Siyasa",
    "filter.clear": "Share Tace",
    "project.total": "Jimillar Ayyuka",
    "project.active": "Aiki",
    "project.completed": "Kammala",
    "project.flagged": "Alama",
    "project.budget": "Kasafin Kudi",
    "project.released": "An Saki",
    "project.spent": "An Kashe",
    "project.trustscore": "Amintacce Maki",
    "project.overview": "Dubawa",
    "project.financial": "Rarraba Kudi",
    "project.inspection": "Duba Aiki & Tabbatarwa",
    "project.documents": "Takardu & Biyayya",
    "project.milestones": "Matakai",
    "contractor.name": "Dan kwangila",
    "contractor.rating": "Kimar Aiki",
    "contractor.cac": "Rijistar CAC",
    "contractor.bpp": "BPP Sharewa",
    "contractor.contracts": "Kwangiloli",
    "citizen.submit": "Gabatar da Rahoton",
    "citizen.upload": "Loda Hotunan Aiki",
    "citizen.gps": "Wurin GPS",
    "citizen.ai": "AI Bincike",
    "citizen.badges": "Bajin ku",
    "citizen.reports": "Rahotannin ku",
    "role.switch": "Canza Matsayi",
    "role.citizen": "Dan kasa / CSO",
    "role.executive": "Shugabanci / Gudanarwa",
    "role.ministry": "Ma'aikata / MDA",
    "role.contractor": "Dan kwangila Portal",
    "role.auditor": "Mai duba / EFCC",
    "export.pdf": "Fitar da PDF",
    "export.csv": "Fitar da CSV",
    "export.json": "Fitar da JSON (OCDS)",
    "trust.breakdown": "Rarraba Amintacce Maki",
    "trust.anomalies": "Gano Matsala",
    "trust.simulator": "Mai Kwaikwayo",
    "common.loading": "Ana lodi...",
    "common.error": "Kuskure ya faru",
    "common.close": "Rufe",
    "common.view": "Duba Cikakkai",
    "common.back": "Geri",
  },
  yo: {
    "app.title": "The Clear Contract Nigeria",
    "app.subtitle": "Ipinle Eto Aabo ti Orilẹ & Ilana Ifilọlẹ",
    "app.tagline": "Ṣii. Onídawọ. Ṣe afihan.",
    "nav.home": "Ile",
    "nav.map": "Maapu Orilẹ",
    "nav.dashboard": "Dasibodu",
    "nav.projects": "Awọn iṣẹ",
    "nav.contractors": "Agbawọṣe",
    "nav.verify": "Jẹri iṣẹ",
    "nav.export": "Awọn ijabọ & data",
    "nav.trust": "Igbẹkẹle Matrix",
    "search.placeholder": "Wa nipasẹ koodu iṣẹ, agbawọṣe, ipinle, MDA...",
    "filter.sector": "Ẹka",
    "filter.state": "Ipinle",
    "filter.status": "Ipo",
    "filter.risk": "Ipele ewu",
    "filter.lga": "Agbegbe",
    "filter.zone": "Agbegbe Iselu",
    "filter.clear": "Nu àlẹmọ",
    "project.total": "Gbogbo Awọn iṣẹ",
    "project.active": "Ti nṣiṣe",
    "project.completed": "Ti pari",
    "project.flagged": "Ti samisi",
    "project.budget": "Isuna ti a fọwọsi",
    "project.released": "Ti tu silẹ",
    "project.spent": "Ti lo",
    "project.trustscore": "Igbẹkẹle Dimegrio",
    "project.overview": "Akopọ",
    "project.financial": "Pinpin Isuna",
    "project.inspection": "Ayẹwo aaye & ijẹrisi AI",
    "project.documents": "Awọn iwe & ibamu",
    "project.milestones": "Awọn ikoko",
    "contractor.name": "Agbawọṣe",
    "contractor.rating": "Iṣe iṣe",
    "contractor.cac": "Iforukọsilẹ CAC",
    "contractor.bpp": "BPP Imudara",
    "contractor.contracts": "Awọn adehun",
    "citizen.submit": "Fi ijabọ aaye silẹ",
    "citizen.upload": "Ṣe agbega awọn fọto aaye",
    "citizen.gps": "Ipo GPS",
    "citizen.ai": "AI Itupalẹ",
    "citizen.badges": "Awọn baaji rẹ",
    "citizen.reports": "Awọn ijabọ rẹ",
    "role.switch": "Yi ipa pada",
    "role.citizen": "Ara ilu / CSO",
    "role.executive": "Alakoso / Alase",
    "role.ministry": "Ile-iṣẹ / MDA",
    "role.contractor": "Agbawọṣe Portal",
    "role.auditor": "Oluyẹwo / EFCC",
    "export.pdf": "Gbejade PDF",
    "export.csv": "Gbejade CSV",
    "export.json": "Gbejade JSON (OCDS)",
    "trust.breakdown": "Pinpin Igbẹkẹle Dimegrio",
    "trust.anomalies": "Wiwari Ajeji",
    "trust.simulator": "Oluyaworan",
    "common.loading": "N gbera...",
    "common.error": "Aṣiṣe kan waye",
    "common.close": "Pa",
    "common.view": "Wo Apejuwe",
    "common.back": "Pada",
  },
  ig: {
    "app.title": "The Clear Contract Nigeria",
    "app.subtitle": "Mba Nleba Akụrụngwa Mba & Ihe Ngosi Nhazi",
    "app.tagline": "Meghe. Akaụntụ. Gosi.",
    "nav.home": "Ulo",
    "nav.map": "Map nke Mba",
    "nav.dashboard": "Dashboard",
    "nav.projects": "Ọrụ",
    "nav.contractors": "Ndị ọrụ nkwekọrịta",
    "nav.verify": "Nyochaa ọrụ",
    "nav.export": "Mkpesa & Data",
    "nav.trust": "Tụkwasị obi Matrix",
    "search.placeholder": "Chọọ site na koodu ọrụ, onye ọrụ nkwekọrịta, steeti, MDA...",
    "filter.sector": "Ngalaba",
    "filter.state": "Steeti",
    "filter.status": "Ọnọdụ",
    "filter.risk": "Ọkwa Ihe egwu",
    "filter.lga": "LGA",
    "filter.zone": "Mpaghara Ọchịchị",
    "filter.clear": "Kpochapụ Ihe nzacha",
    "project.total": "Ngụkọta Ọrụ",
    "project.active": "Na-arụ ọrụ",
    "project.completed": "Emechara",
    "project.flagged": "Ederede",
    "project.budget": "Ego akwadoro",
    "project.released": "Ahapụla",
    "project.spent": "Efuru",
    "project.trustscore": "Tụkwasị obi Akara",
    "project.overview": "Nchịkọta",
    "project.financial": "Nkewa Ego",
    "project.inspection": "Nyocha saịtị & AI Nyocha",
    "project.documents": "Akwụkwọ & nnabata",
    "project.milestones": "Ihe ndị a rụzuru",
    "contractor.name": "Onye ọrụ nkwekọrịta",
    "contractor.rating": "Ọkwa arụmọrụ",
    "contractor.cac": "CAC Ndebanye aha",
    "contractor.bpp": "BPP Mkpochapụ",
    "contractor.contracts": "Nkwekọrịta",
    "citizen.submit": "Nyefee akụkọ saịtị",
    "citizen.upload": "Bulite foto saịtị",
    "citizen.gps": "GPS Ọnọdụ",
    "citizen.ai": "AI Nyocha",
    "citizen.badges": "Baajị gị",
    "citizen.reports": "Akụkọ gị",
    "role.switch": "Gbanwee Ọrụ",
    "role.citizen": "Nwa amaala / CSO",
    "role.executive": "Onye isi ala / Onye isi",
    "role.ministry": "Mịnịstrị / MDA",
    "role.contractor": "Onye ọrụ nkwekọrịta Portal",
    "role.auditor": "Onye nyocha / EFCC",
    "export.pdf": "Mbuputa PDF",
    "export.csv": "Mbuputa CSV",
    "export.json": "Mbuputa JSON (OCDS)",
    "trust.breakdown": "Nkewa Tụkwasị obi Akara",
    "trust.anomalies": "Nchọpụta Ihe ịtụnanya",
    "trust.simulator": "Onye na-eme ihe atụ",
    "common.loading": "Na-ebu...",
    "common.error": "Ihe mmeghe mere",
    "common.close": "Mechie",
    "common.view": "Lelee nkọwa",
    "common.back": "Laghachi",
  },
  pcm: {
    "app.title": "The Clear Contract Nigeria",
    "app.subtitle": "National Infrastructure & Procurement Transparency Platform",
    "app.tagline": "Open. Accountable. Transparent.",
    "nav.home": "Home",
    "nav.map": "National Map",
    "nav.dashboard": "Dashboard",
    "nav.projects": "Projects",
    "nav.contractors": "Contractors",
    "nav.verify": "Verify Project",
    "nav.export": "Reports & Data",
    "nav.trust": "Trust Matrix",
    "search.placeholder": "Search by project code, contractor, state, MDA...",
    "filter.sector": "Sector",
    "filter.state": "State",
    "filter.status": "Status",
    "filter.risk": "Risk Level",
    "filter.lga": "LGA",
    "filter.zone": "Geo-Political Zone",
    "filter.clear": "Clear Filters",
    "project.total": "Total Projects",
    "project.active": "Active",
    "project.completed": "Completed",
    "project.flagged": "Flagged",
    "project.budget": "Approved Budget",
    "project.released": "Released",
    "project.spent": "Spent",
    "project.trustscore": "Trust Score",
    "project.overview": "Overview",
    "project.financial": "Financial Breakdown",
    "project.inspection": "Site Inspection & AI Verification",
    "project.documents": "Documents & Compliance",
    "project.milestones": "Milestones",
    "contractor.name": "Contractor",
    "contractor.rating": "Performance Rating",
    "contractor.cac": "CAC Registration",
    "contractor.bpp": "BPP Clearance",
    "contractor.contracts": "Contracts",
    "citizen.submit": "Submit Field Report",
    "citizen.upload": "Upload Site Photos",
    "citizen.gps": "GPS Location",
    "citizen.ai": "AI Analysis",
    "citizen.badges": "Your Badges",
    "citizen.reports": "Your Reports",
    "role.switch": "Switch Role",
    "role.citizen": "Citizen / CSO",
    "role.executive": "Presidency / Executive",
    "role.ministry": "Ministry / MDA",
    "role.contractor": "Contractor Portal",
    "role.auditor": "Auditor / EFCC",
    "export.pdf": "Export PDF",
    "export.csv": "Export CSV",
    "export.json": "Export JSON (OCDS)",
    "trust.breakdown": "Trust Score Breakdown",
    "trust.anomalies": "Anomaly Detection",
    "trust.simulator": "Scenario Simulator",
    "common.loading": "Loading...",
    "common.error": "Error happun",
    "common.close": "Close am",
    "common.view": "See Details",
    "common.back": "Go back",
  },
};

export const PROJECT_IMAGES: Record<string, string> = {
  "LAG-HWY-001": "https://storage.googleapis.com/dala-prod/7f228a51-2b3d-4c80-9e97-4e42c0bfa0b5.png",
  "LAG-BDG-002": "https://storage.googleapis.com/dala-prod/fb4f24bb-6f9d-4217-9a12-1f606a0b4392.png",
  "ABJ-HSP-003": "https://storage.googleapis.com/dala-prod/9a4f1d38-2922-47a5-9aed-cf61f1e7f0e2.png",
  "KNG-SCH-004": "https://storage.googleapis.com/dala-prod/fb0ba01e-5230-4a1c-9a5b-ba846c9e6f42.png",
  "PHC-WAT-005": "https://storage.googleapis.com/dala-prod/9f0f46b8-18b9-407b-bf1b-0cac580c0e3e.png",
  "ABJ-REN-006": "https://storage.googleapis.com/dala-prod/09f0a6b5-83f8-46b0-ba86-66e81f970a0b.png",
  "KNG-PWR-007": "https://storage.googleapis.com/dala-prod/519a0a96-06f5-4b1a-9a4b-3b1a342a2faa.png",
  "LAG-TEL-008": "https://storage.googleapis.com/dala-prod/5f0c3e50-2a0f-4cd0-a3a8-1fea242a8f32.png",
};

export const CIVIC_LINKS = [
  { label: "Bureau of Public Procurement (BPP)", href: "https://www.bpp.gov.ng" },
  { label: "Infrastructure Concession Regulatory Commission (ICRC)", href: "https://www.icrc.gov.ng" },
  { label: "Nigeria Sovereign Investment Authority (NSIA)", href: "https://nsia.com.ng" },
  { label: "Federal Ministry of Works", href: "https://www.worksandhousing.gov.ng" },
  { label: "Open Contracting Partnership (OCP)", href: "https://www.open-contracting.org" },
  { label: "Public Procurement Act 2007", href: "https://www.bpp.gov.ng/ppa" },
];

export const HELPLINES = [
  { label: "BPP Whistleblower Hotline", phone: "0800-BPP-WATCH" },
  { label: "EFCC Corruption Report", phone: "0800-EFCC-NOW" },
  { label: "ICPC Anti-Corruption", phone: "0800-ICPC-REPORT" },
  { label: "Presidential Complaints Centre", phone: "0800-PCC-HELP" },
];

export function t(key: string, lang: string): string {
  return translations[lang]?.[key] || translations["en"]?.[key] || key;
}